import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

function About() {
  return <div> About Page</div>;
}

export default About;
