import "./globals.css";
import { Poppins } from "next/font/google";

import MainNavigation from "./ui/MainNavigation/MainNavigation";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Architects near me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MainNavigation />

        {children}
      </body>
    </html>
  );
}
